### ISSUE TITLE
Security trouble 

### ISSUE THREAD

**Issue by roma2341** [sergkh/vntu-web-mblog#5]
I can't register a new user. Nothing happen. I watch database file - no new users in it ,only default admin  record excists, which added by createAdminUser() function. Why ???

**Comment by sergkh** [comment]
Thats because security configuration was not finished yet. Latest version is not always stable and some parts of it can be changed. But now it's fixed.  Thanks for the attentiveness!

**Comment by roma2341** [comment]
thks! It's work fine, i had additional problem with logining because i use:
name="loginform_password" in my html
so i had to add .passwordParameter("login_password") call to my security config.

**Comment by sergkh** [comment]
Login and password parameters should match default names (`j_username` and `j_password`) or better be configured manually.
